spring:
  application:
    name: clinic-appointment

  datasource:
    url: ${SUPABASE_DB_URL:jdbc:postgresql://aws-1-ap-south-1.pooler.supabase.com:5432/postgres?sslmode=require}
    username: postgres.sbjnwfcjcqvtwuwrdcvt
    password: pFOZeSZwWPDKqeM8
    driver-class-name: org.postgresql.Driver

    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 20000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

    sql:
      init:
        mode: always
  mail:
    host: smtp.gmail.com
    port: 587
    username: viethuu1205@gmail.com
    password: gakv tyrz igjg leay
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    try-it-out-enabled: true
    operations-sorter: method
    pageable-parameter-string: true
  api-docs:
    enabled: true
    path: /v3/api-docs

jwt:
  secretKey: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  issuer: tuda24
  accessTokenExpiration: 86400000

google:
  client-id: 674544856247-s4fkj638dt6rqcs154tg8dpr8sbkivp5.apps.googleusercontent.com

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - metrics

internal:
  api:
    base-url: ${INTERNAL_API_BASE_URL:http://localhost:8080}
    admin-token: ${INTERNAL_ADMIN_TOKEN:}